### PR TITLE
Change return value for realm roles scope

### PR DESCRIPTION
**Pull request by klusekP**

### CODE REVIEW

**Review by mainick — APPROVED** [review]
it's OK

**Review by mainick — CHANGES_REQUESTED** [review]
You can also change the annotation of the `getClientRoles` method: as you did for the `getRealRoles` method, it must not return the null value

**Comment by gubug** [comment]
> You can also change the annotation of the `getClientRoles` method: as you did for the `getRealRoles` method, it must not return the `null` value

yes please, I have this error when realm roles are null instead of []
`Only arrays and Traversables can be unpacked`

also, isn't `getRealRoles()` supposed to be named `getRealmRoles()` ? looks like a typo

**Comment by tungmv7** [comment]
I got the same error without this pr. Please merge and release this!

**Pull request closed without merging**
